modified config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -345,52 +345,52 @@ jobs:
             ansible-playbook -i inventory.txt deploy-backend.yml
       - destroy-environment
 
-  # smoke-test:
-  #   docker:
-  #     - image: python:alpine3.16
-  #   steps:
-  #     - checkout
-  #     - attach_workspace:
-  #         at: ~/
-  #     - run:
-  #         name: Install image dependencies
-  #         command: |
-  #           apk add --update curl nodejs npm
-  #           pip install awscli
+  smoke-test:
+    docker:
+      - image: python:alpine3.16
+    steps:
+      - checkout
+      - attach_workspace:
+          at: ~/
+      - run:
+          name: Install image dependencies
+          command: |
+            apk add --update curl nodejs npm
+            pip install awscli
 
-  #     - run:
-  #         name: Get backend url and perform smoke test on the backend server
-  #         command: |
-  #           export BACKEND_IP=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
-  #           export API_URL="http://${BACKEND_IP}:3030"
-  #           echo "API URL: ${API_URL}"
-  #           echo "Wait for backend to become available..."
-  #           sleep 180s
-  #           echo "Attempting to reach backend..."
-  #           if curl "${API_URL}/api/status" | grep "ok"
-  #           then
-  #             echo "Backend status OK"
-  #             exit 0
-  #           else
-  #             echo "Backend status NOT OK"
-  #             exit 1
-  #           fi
+      - run:
+          name: Get backend url and perform smoke test on the backend server
+          command: |
+            export BACKEND_IP=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
+            export API_URL="http://${BACKEND_IP}:3030"
+            echo "API URL: ${API_URL}"
+            echo "Wait for backend to become available..."
+            sleep 180s
+            echo "Attempting to reach backend..."
+            if curl "${API_URL}/api/status" | grep "ok"
+            then
+              echo "Backend status OK"
+              exit 0
+            else
+              echo "Backend status NOT OK"
+              exit 1
+            fi
 
-  #     - run:
-  #         name: Frontend smoke test
-  #         command: |
-  #           URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
-  #           echo ${URL} 
-  #           if curl -s ${URL} | grep "Welcome"
-  #           then
-  #               # Change this to 0 after the job fails
-  #             return 0
-  #           else
-  #             return 1
-  #           fi
+      - run:
+          name: Frontend smoke test
+          command: |
+            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
+            echo ${URL} 
+            if curl -s ${URL} | grep "Welcome"
+            then
+                # Change this to 0 after the job fails
+              return 1
+            else
+              return 1
+            fi
 
-  #     - destroy-environment
-  #     - revert-migrations
+      - destroy-environment
+      - revert-migrations
 
 
   # cloudfront_update:
@@ -459,28 +459,28 @@ jobs:
 workflows:
   default:
     jobs:
-      - build-frontend
-      - build-backend
-      - test-frontend:
-          requires: [build-frontend]
-      - test-backend:
-          requires: [build-backend]
-      - scan-backend:
-          requires: [build-backend]
-      - scan-frontend:
-          requires: [build-frontend]
-      - deploy-infrastructure:
-          requires: [test-frontend, test-backend, scan-frontend, scan-backend]
-      - configure-infrastructure:
-          requires: [deploy-infrastructure]
-      - run_migrations:
-          requires: [configure-infrastructure]
-      - deploy_backend:
-          requires: [run_migrations]
-      - deploy_frontend:
-          requires: [run_migrations]
-      # - smoke-test:
-      #     requires: [deploy_backend, deploy_frontend]
+      # - build-frontend
+      # - build-backend
+      # - test-frontend:
+      #     requires: [build-frontend]
+      # - test-backend:
+      #     requires: [build-backend]
+      # - scan-backend:
+      #     requires: [build-backend]
+      # - scan-frontend:
+      #     requires: [build-frontend]
+      # - deploy-infrastructure:
+      #     requires: [test-frontend, test-backend, scan-frontend, scan-backend]
+      # - configure-infrastructure:
+      #     requires: [deploy-infrastructure]
+      # - run_migrations:
+      #     requires: [configure-infrastructure]
+      # - deploy_backend:
+      #     requires: [run_migrations]
+      # - deploy_frontend:
+      #     requires: [run_migrations]
+      - smoke-test:
+          # requires: [deploy_backend, deploy_frontend]
       # - cloudfront_update:
       #     requires: [smoke-test]
       # - cleanup:
